export default {
	"en-US": {
		home: 'home',
		trade: "trade",
		consult: "consult",
		mine: "mine",

		// title 
		"pages-login-login": "login",
		"pages-news-index": "Trading",
		"pages-zixun-index": "Enquiries",
		"pages-index-tuandui-tuandui": "My Team",
		"pages-index-mujuanj-mujuanj": "Fundraising",
		"pages-news-newdel-newdel": "Details",
		"pages-news-chongzhi-chongzhi": "Recharge",
		"pages-news-tixian-tixian": "Withdraw",
		"pages-news-jiaoyi-jiaoyi": "Transaction History",
		"pages-mine-InviteFriends-InviteFriends": "My Invitation Code",
		"pages-mine-ChangePassword-ChangePassword": "Change password",
		"pages-mine-TransactionCode-TransactionCode": "Trading Password",
		"pages-mine-MessageBoard-MessageBoard": "Message Board",
		"pages-mine-dizhi-dizhi": "Link",
		"pages-mine-dizhi-tianjia-tianjia": "Add Address",
		"pages-index-mujuan-mujuan": "Donation details",
		"pages-index-index":"Register",

		// login
		"P_Email": "Please enter your email address",
		"P_Account": "Select account",
		"P_Password": "Please enter your password",
		"L_Register": "Don't have an account yet, go and register",
		"L_Forgotten": "Forgot your password?",
		"L_t_Email": "Please enter your correct email address",
		"L_T_Account": "Please enter your chosen login",
		"L_T_Success": "Sign in successfully",
		"Unregistered": "You are not yet registered, please go to Register",
		
		
		// 注册
		"P_Code": "Verification code",
		"Nickname": "Nickname",
		"T_Nickname":"Please enter a nickname",
		"T_passsword":"New password",
		"Password":"Password",
		"Confirm_Password":"Confirm Password",
		"Invitation_Code":"Invitation Code",
		"Required_field":"Required",
		"Verification_code":"code",
		"Email":"Email",
		"T_R_password":"Confirm Password",
		"P_Invitation_Code":"Invitation code",
		"Agreement":"Agreement",
		"Read":"Read and agree to",
		"Confirm_Registration":"Confirm Registration",
		"getCode":"Get code",
		"Recapture":"Resend",
		"Authorisation":"Licensing agreements",
		"Privacy":"Privacy Agreement",
		"I_know":"I know",
		"send_success":"Send successfully",
		"inconsistent":"Two inconsistent passwords",
		"R_success":"Registration is successful",
		
		// 忘记密码
		"Select_account":"Select account",
		"New_password":"New password",
		"Reset_password":"Reset password",
		"T_T_select_login":"Please enter your choice of login",
		"P_R_S":"Password reset successful",
		"Repeat_password":"Repeat password",
		"go_Register":"You are not yet registered, please go to Register",
		
		// 邀请好友
		invitation_code: 'Code',
		leshi: 'Leshi',
		recharge_currency: 'Recharge Currency',

		// 募捐
		recharge_currency: 'Recharge Currency',
		recharge_quantity: 'Recharge Quantity',
		recharge_QRcode: 'Recharge QRCode',
		copy: 'copy',
		upload_voucher: 'Upload Voucher',
		donation_notes: 'Donation Dotes',
		donation_notes1: '1.Please make sure the recharge address is the address starting with TRC20 type T.',
		donation_notes2: '2.The minimum recharge amount is 5U. Less than the minimum recharge amount will not be credited and cannot be returned.',
		donation_notes3: '3.Please do not solicit any non-USDT assets (chain type: TRC20) to the above address, otherwise the assets will not be recoverable.',
		donation_notes4: '4.Your collection address will not change often, you can repeat your collection, if there is a change, a notification will be given on the collection page.',
		donation_notes5: '5.Please make sure your computer, cell phone and browser are secure to prevent information leakage or tampering.',
		donation_notes6: '6. Thank you for your good deeds, and may you have peace in your life.',
		recharge_now: 'Recharge Now',
		// 充值(注释部分为同募捐已经定义过变量，不再重复)
		//recharge_currency: '充值币种',
		//recharge_quantity: '充值数值',
		//recharge_QRcode: '充值二维码',
		//copy: '复制',
		//upload_voucher: '上传凭证',
		recharge_notes: 'Recharge Notes',
		//donation_notes1: '1.请确认充币地址是TRC20型T开头的地址。',
		donation_notes22: '2.The minimum recharge amount is 100U. Less than the minimum recharge amount will not be credited and cannot be returned.',
		//donation_notes3: '3.请勿向上述地址募捐任何非USDT资产（链类型：TRC20），否则资产不可找回。',
		//donation_notes4: '4.您的募捐地址不会经常改变，可以重复募捐，如有改变，将会在募捐页面给予通知。',
		//donation_notes5: '5.请务必确认您的电脑，手机及浏览器安全，防止信息泄露或被篡改。',
		//recharge_now: '立即充值',

		// 我的团队
		team_name: 'Team',
		team_size: 'Team size',
		team_total: 'Team total',
		sub_user: 'Subordinate Users',

		// 提现
		address_placeholder: 'Please enter or paste the usual address',
		usual_address: 'Link',
		quota_placeholder: 'withdrawal amount',
		all: 'All',
		forgot_payment_password: 'Forgot password',
		password_placeholder: 'Payment password',
		withdraw: 'Withdraw',
		//------USDT提现--------
		USDT_notes: 'USDT Withdrawal Notes',
		USDT_notes1: '1.Please make sure your address is the address beginning with TRC20 type T.',
		USDT_notes2: '2.Withdrawal fee is 5%.',
		USDT_notes3: '3.The minimum withdrawal amount is 100U. Any amount less than the minimum withdrawal amount will not be credited and cannot be returned.',
		USDT_notes4: '4.Please make sure that the target address exists and is activated, otherwise the withdrawal will fail and the assets will not be recovered.',
		//donation_notes5: '5.请务必确认您的电脑，手机及浏览器安全，防止信息泄露或被篡改。',
		USDT_notes6: '6.Withdrawal requests are submitted on Thursdays and Fridays, but no withdrawals are allowed at other times.',
		USDT_notes_t: 'Withdrawal requests are submitted on Thursdays and Fridays, but no withdrawals are allowed at other times.',
		//------SHIB提现--------
		SHIB_notes: 'SHIB Withdrawal Notes',
		SHIB_notes1: '1.If your withdrawal amount is between 1 million and 5 million, please make sure your address is a TRC20 type address for receiving USDT; if your withdrawal amount is more than 5 million, please make sure your address is an ERC20 type address.',
		SHIB_notes2: '2.If you withdraw cash between 1 million and 5 million, the handling fee is 10%, and the withdrawal will be made to your address with the converted USDT amount; if you withdraw cash over 5 million, the handling fee is 5%.',
		SHIB_notes3: '3.The minimum withdrawal amount is 1 million SHIB. and cannot be returned.',
		//USDT_notes4: '4.Please make sure that the target address exists and is activated, otherwise the withdrawal will fail and the assets will not be recovered.',
		//donation_notes5: '5.请务必确认您的电脑，手机及浏览器安全，防止信息泄露或被篡改。',
		//USDT_notes6: '6.提交提现申请时间为每周四、周五，其他时间不允许提现。'	,
		//------NFT提现--------
		NFT_notes: 'NFT Withdrawal Notes',
		//USDT_notes1: '1.Please make sure your address is the address beginning with TRC20 type T.',
		NFT_notes2: '2.Withdrawal fee is 5%.',
		NFT_notes3: '3.The minimum withdrawal amount is 1 million NFT. and cannot be returned.',
		//USDT_notes4: '4.请务必确认目标地址是否存在且被激活，否则将会导致提币失败,且资产不可找回。',
		//donation_notes5: '5.请务必确认您的电脑，手机及浏览器安全，防止信息泄露或被篡改。',
		//USDT_notes6: '6.提交提现申请时间为每周四、周五，其他时间不允许提现。'	,
		//------GLZ提现--------(暂未开放)

		// 募捐明细
		donation_details: 'Donation details',

		// 交易记录
		trade_history: 'Trade History',
		recharge: 'Recharge',
		//withdraw: 'Withdraw',
		frozen: 'Frozen',
		daily_delivery: 'Daily Delivery',
		direct_reward: 'DirectReward',
		team_reward: 'TeamReward',
		pending: 'Pending',
		approved: 'Approved',
		refused: 'Refused',
		fee: 'Fee',


		// 补充
		"Investment":"level",
		"None":"None",
		"News":"News",
		"more":"more",
		"Donation":"Donation",
		"Breakdown":"Details",
		"Uploaded":"Uploaded",
		"amount":"amount",
		"Minimum":"Minimum donation amount",
		"vouchers":"Please upload proof of donation",
		"Successful_transaction":"Successful transaction",
		"Tips":"Tip",
		"save_album":"Sure to save to album?",
		"Saved_successfully":"Saved successfully",
		"Failed_to_save":"Failed to save",
		"Reproduction_success":"Copy successful",
		"Copy_failure":"Failed to copy",

		"people_Number":"Platform numbers",
		"no_nickname":"No nickname at the moment",
		"Invite_a_friend":"Invite Friends	",
		"Change_password":"Change password",
		"Trading_Password":"Trading password",
		"Message_Board":"Message Board",
		"Add_common_address":"Add Link",
		"Log_out":"Log out",
		"sure_Log_out":"Are you sure you want to log out of your current account?",
		"save":"Save",
		"Change_transaction":"Change your trading password",
		"Change_Login":"Change your login password",
		"Suggestions":"Please fill in your questions and suggestions",
		"Thank_you":"Thank you for your support and assistance, we look forward to providing you with a better service.",
		"submit":"Submit",
		"Feedback_Success":"Feedback Success",
		"Not_available":"No",
		"Added_successfully":"Add Success",
		"transaction_password":"Please enter your trading password",
		"add":"add",
		
		"text1":"No access",
		"text2":"选择图片",
		"text3":"Please enter a link",
		"text4":"text",
		"text5":"text",
		"text6":"text",
		"text7":"text",
		"text8":"text",
		"text9":"text",
		"text10":"text",

	},
	"en-CN": {

		home: '首页',
		trade: "交易",
		consult: "资讯",
		mine: "我的",

		// title
		"pages-login-login": "登录",
		"pages-news-index": "交易",
		"pages-zixun-index": "咨询",
		"pages-index-tuandui-tuandui": "我的团队",
		"pages-index-mujuanj-mujuanj": "募捐",
		"pages-news-newdel-newdel": "详情",
		"pages-news-chongzhi-chongzhi": "充值",
		"pages-news-tixian-tixian": "提现",
		"pages-news-jiaoyi-jiaoyi": "交易记录",
		"pages-mine-InviteFriends-InviteFriends": "我的邀请码",
		"pages-mine-ChangePassword-ChangePassword": "修改密码",
		"pages-mine-TransactionCode-TransactionCode": "交易密码",
		"pages-mine-MessageBoard-MessageBoard": "留言板",
		"pages-mine-dizhi-dizhi": "常用地址",
		"pages-mine-dizhi-tianjia-tianjia": "添加地址",
		"pages-index-mujuan-mujuan": "募捐明细",

		// login
		"P_Email": "请输入邮箱",
		"P_Account": "选择账号",
		"P_Password": "请输入密码",
		"L_Register": "还没账号,去注册",
		"L_Forgotten": "忘记密码",
		"L_t_Email": "请输入正确的邮箱地址",
		"L_T_Account": "请输入选择登录账号",
		"L_T_Success": "登录成功",
		"Unregistered": "您还未注册，请前往注册",
		"pages-index-index":"注册",
		
		// 注册
		"P_Code": "请输入验证码",
		"Nickname": "昵称",
		"T_Nickname":"请输入昵称",
		"T_passsword":"请输入密码",
		"Password":"密码",
		"Confirm_Password":"确认密码",
		"Invitation_Code":"邀请码",
		"Required_field":"必填",
		"Verification_code":"验证码",
		"Email":"邮箱",
		"T_R_password":"请再次输入密码",
		"P_Invitation_Code":"请输入邀请码",
		"Agreement":"用户协议",
		"Read":"阅读并同意",
		"Confirm_Registration":"确认注册",
		"getCode":"获取验证码",
		"Recapture":"重新获得",
		"Authorisation":"许可协议",
		"Privacy":"隐私协议",
		"I_know":"我知道",
		"send_success":"验证码发送成功",
		"inconsistent":"两次密码不一致",
		"R_success":"注册成功",
		
		// 忘记密码
		"Select_account":"选择账号",
		"New_password":"新的密码",
		"Reset_password":"重置密码",
		"T_select_login":"请选择登录账号",
		"P_R_S":"密码重置成功",
		"Repeat_password":"重复密码",
		"go_Register":"您还未注册，请前往注册",

		// 邀请好友
		invitation_code: '我的邀请码',
		leshi: 'SHIBA',

		// 募捐
		recharge_currency: '充值币种',
		recharge_quantity: '充值数值',
		recharge_QRcode: '充值二维码',
		copy: '复制',
		upload_voucher: '上传凭证',
		donation_notes: '募捐注意事项',
		donation_notes1: '1.请确认充币地址是TRC20型T开头的地址。',
		donation_notes2: '2.最小募捐金额5U。小于最小充币金额的将不会到账且无法退回。',
		donation_notes3: '3.请勿向上述地址募捐任何非USDT资产（链类型：TRC20），否则资产不可找回。',
		donation_notes4: '4.您的募捐地址不会经常改变，可以重复募捐，如有改变，将会在募捐页面给予通知。',
		donation_notes5: '5.请务必确认您的电脑，手机及浏览器安全，防止信息泄露或被篡改。',
		donation_notes6: '6.感谢您的善举，愿您一生平安。',
		recharge_now: '立即充值',
		// 充值(注释部分为同募捐已经定义过变量，不再重复)
		//recharge_currency: '充值币种',
		//recharge_quantity: '充值数值',
		//recharge_QRcode: '充值二维码',
		//copy: '复制',
		//upload_voucher: '上传凭证',
		recharge_notes: '充值注意事项',
		//donation_notes1: '1.请确认充币地址是TRC20型T开头的地址。',
		donation_notes22: '2.最小充币金额100U。小于最小充币金额的将不会到账且无法退回。',
		//donation_notes3: '3.请勿向上述地址募捐任何非USDT资产（链类型：TRC20），否则资产不可找回。',
		//donation_notes4: '4.您的募捐地址不会经常改变，可以重复募捐，如有改变，将会在募捐页面给予通知。',
		//donation_notes5: '5.请务必确认您的电脑，手机及浏览器安全，防止信息泄露或被篡改。',
		//recharge_now: '立即充值',

		//我的团队
		team_name: '的团队',
		team_size: '团队总人数',
		team_total: '团队总',
		sub_user: '下级用户',

		// 提现
		address_placeholder: '请输入或长按粘贴地址',
		usual_address: '常用地址',
		quota_placeholder: '请输入提现额度',
		all: '全部',
		forgot_payment_password: '忘记支付密码',
		password_placeholder: '请输入资金密码',
		withdraw: '提现',
		//------USDT提现--------
		USDT_notes: 'USDT提现注意事项',
		USDT_notes1: '1.请确认您的地址是TRC20型T开头的地址。',
		USDT_notes2: '2.提现手续费为5%。',
		USDT_notes3: '3.最少提币金额100U。小于最小提币金额的将不会到账且无法退回。',
		USDT_notes4: '4.请务必确认目标地址是否存在且被激活，否则将会导致提币失败,且资产不可找回。',
		//donation_notes5: '5.请务必确认您的电脑，手机及浏览器安全，防止信息泄露或被篡改。',
		USDT_notes6: '6.提交提现申请时间为每周四、周五，其他时间不允许提现。',
		USDT_notes_t: '提交提现申请时间为每周四、周五，其他时间不允许提现。',
		//------SHIB提现--------
		//----前台校验100w-500w 10% 500w以上 5%，最小提现金额是100w 
		//----后台系统需要计算距离最后一次充值的天数
		SHIB_notes: 'SHIB提现注意事项',
		SHIB_notes1: '1.如果您提现金额在100万到500万之间，请确认您的地址是TRC20型收USDT的地址；如果您提现金额500万以上，请确认您的地址是ERC20型的地址。',
		SHIB_notes2: '2.如果您提现金额在100万到500万之间，手续费为10%，提现将会以折算USDT金额提现到您的地址;如果您提现金额500万以上,手续费为5%。',
		SHIB_notes3: '3.最少提币金额100万SHIB。小于最小提币金额的将不会到账且无法退回。',
		//USDT_notes4: '4.请务必确认目标地址是否存在且被激活，否则将会导致提币失败,且资产不可找回。',
		//donation_notes5: '5.请务必确认您的电脑，手机及浏览器安全，防止信息泄露或被篡改。',	
		//USDT_notes6: '6.提交提现申请时间为每周四、周五，其他时间不允许提现。'	,
		//------NFT提现--------			
		NFT_notes: 'NFT提现注意事项',
		//USDT_notes1: '1.请确认您的地址是TRC20型T开头的地址。',
		NFT_notes2: '2.提现手续费为5%。',
		NFT_notes3: '3.最少提币金额10万NFT。小于最小提币金额的将不会到账且无法退回。',
		//USDT_notes4: '4.请务必确认目标地址是否存在且被激活，否则将会导致提币失败,且资产不可找回。',
		//donation_notes5: '5.请务必确认您的电脑，手机及浏览器安全，防止信息泄露或被篡改。',
		//USDT_notes6: '6.提交提现申请时间为每周四、周五，其他时间不允许提现。'	,
		//------GLZ提现--------(暂未开放)

		// 募捐明细
		donation_details: '募捐明细',

		// 交易记录
		trade_history: '交易记录',
		recharge: '充值',
		//withdraw: '提现',
		frozen: '冻结',
		daily_delivery: '日送',
		direct_reward: '直推奖励',
		team_reward: '团队奖励',
		pending: '等待审核',
		approved: '已审核',
		refused: '拒绝',
		fee: '手续费',
		
		
		// 补充
		"Investment":"投资级别",
		"None":"无",
		"News":"新闻",
		"more":"更多",
		"Donation":"捐款",
		"Breakdown":"明细",
		"Uploaded":"已上传",
		"amount":"请输入金额",
		"Minimum":"最小募捐金额",
		"vouchers":"请上传凭证",
		"Successful_transaction":"交易成功",
		"Tips":"提示",
		"save_album":"确定保存到相册吗",
		"Saved_successfully":"保存成功",
		"Failed_to_save":"保存失败",
		"Reproduction_success":"复制成功",
		"Copy_failure":"复制失败",
		
		
		
		"people_Number":"平台人数",
		"no_nickname":"暂无昵称",
		"Invite_a_friend":"邀请好友",
		"Change_password":"修改密码",
		"Trading_Password":"交易密码",
		"Message_Board":"留言板",
		"Add_common_address":"添加常用地址",
		"Log_out":"退出登录",
		"sure_Log_out":"您确定要退出当前账户的登录吗",
		"save":"保存",
		"Change_transaction":"修改交易密码",
		"Change_Login":"修改登录密码",
		"Suggestions":"请填写您的问题与建议",
		"Thank_you":"感谢您的支持与帮助，我们期待为您带来更优质的服务。",
		"submit":"提交",
		"Feedback_Success":"反馈成功",
		"Not_available":"暂无",
		"Added_successfully":"添加成功",
		"transaction_password":"请输入交易密码",
		
		"add":"添加",
		"text1":"您暂无此权益",
		"text2":"选择图片",
		"text3":"请输入常用地址",
		"text4":"text",
		"text5":"text",
		"text6":"text",
		"text7":"text",
		"text8":"text",
		"text9":"text",
		"text10":"text",
		


	}
}
